Delete instances in archive tab
autolab/Autolab pull request #1321
Opened 2021-04-06 19:28 UTC by amartinez116

Professors are now able to delete instances in the archive tab. Deleting is only possible in the "archive tab". Additionally, in order to reduce accidentally deleting instances, deleting is only possible through selecting students and doing a bulk/singular deletion.  

## Description

Instead of creating a new API endpoint I modified the update_watchlist endpoint. However, if a delete_watchlist_instance endpoint is preferred then the change on doing so would be kinda simple.

## Motivation and Context

When the archive tab contains many many students, it might be useful for professors to delete those instances.

## How Has This Been Tested?

Have students in archive tab. Check on the checkboxes of the student(s) you want to delete. Click on the delete icon and those students should no longer appear in the archive tab.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2021-04-07 09:14 UTC, xinyis991105 commented on app/assets/stylesheets/metrics.scss
> +  background-color: #767676 !important;
Shall we make the button darker so that it stands out more when enabled and allows for a greater contrast when users hover over it?

2021-04-07 09:15 UTC, xinyis991105 commented on app/assets/stylesheets/metrics.scss
> +  background-color: #929191 !important;
Is this meant to be 919191?

2021-04-07 09:33 UTC, xinyis991105 commented on app/assets/javascripts/watchlist.js
> +   // Removes previous click function binded to resolve button
Nitpicking: Shall we update this comment to say "delete button" 😂 ?

2021-04-07 09:37 UTC, xinyis991105 requested changes
Behavior-wise LGTM!
Left some minor comments. I'll review again once these are addressed!

2021-04-10 01:26 UTC, victorhuangwq commented
Oops the rerequest was by accident

2021-04-11 06:39 UTC, xinyis991105 approved these changes
LGTM!

2021-04-11 15:12 UTC, merged