Improve the overview section of the new documentation
autolab/Autolab pull request #1340
Opened 2021-04-26 19:15 UTC by xinyis991105

## Description
This PR improves the overview section of documentation based on feedback from Professor O'Hallaron.

## Motivation and Context
The image in overview needs some correction of wording and a more comprehensive workflow explanation is also added to further explain the image.

## How Has This Been Tested?
mkdocs serve and visit the local host.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2021-04-26 19:17 UTC, xinyis991105 commented on docs/index.md
> +Autolab consists of two services: (1) the Autolab frontend which is implemented using Ruby on Rails, and (2) Tango, the RESTful Python autograding server. <b>Either service can run independently with
The link to tango is removed since based on our discussion last time we will get rid of the tango basics (which tango.md points to) altogether.

2021-04-26 19:57 UTC, ashleyzhang requested changes
Left a few wording suggestions but looks good otherwise. The new diagram looks great too!

2021-04-26 19:57 UTC, ashleyzhang commented on docs/index.md
> +While the Autolab frontend supports Autolab's web application framework, the backend Tango is responsible for distributing and completing autograding jobs, which run in virtual machines or containers
nit: Maybe "We currently support Docker and AWS virtual machines" can go in parentheses after the previous sentence? i.e. "...which run in virtual machines or containers (we currently support Docker and AWS virtual machines)."

2021-04-26 19:57 UTC, ashleyzhang commented on docs/index.md
> +As you can see on the left, the Autolab frontend receives handin files from the clients through either traditional browser interaction or [the command line interface (CLI)](/command-line-interface).
Awesome explanation, just a few minor wording changes I'd suggest - feel free to take them or leave them!

- Change "Tango would add them to a job queue, assign them to available containers/virtual machines for grading through ssh, and shepherd the jobs through the process." to "Tango adds them to a job queue, assigns them to available containers/virtual machines for grading through ssh, and shepherds the jobs through the process." to make it more consistent with the present tense used in previous and later sentences.
- "...inside the VM domain box for Docker at CMU..."
- Change "...we show 3 VM pools, rhel, rhel122, and rhel411, each with potentially different software packages." to we show 3 VM pools - rhel, rhel122, and rhel411 - each with potentially different software packages." I think hyphens just make it a little clearer that those are the image names.
- "...show an example of **an** AWS VM domain..."
- Again to maintain the consistent present tense, "Once a job is done, the feedback will be copied back to Tango through ssh and further sent back to the Autolab frontend through http. The frontend can then display the feedback in the browser or through CLI." can become "Once a job is done, the feedback is copied back to Tango through ssh and sent back to the Autolab frontend through http. The frontend then displays the feedback in the browser or through the CLI."

2021-04-27 17:01 UTC, ashleyzhang approved these changes
LGTM!

2021-04-27 17:05 UTC, merged