Rename Risk Metrics Terminology to Student Metrics
autolab/Autolab pull request #1343
Opened 2021-04-28 00:05 UTC by victorhuangwq

## Description

We have decided to change them to:
at-risk students → students in need
risk-metrics → student metrics 

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2021-04-29 23:45 UTC, amartinez116 commented on app/views/assessments/index.html.erb
> +           <%= link_to "<div class='row metrics'><i class='material-icons left'>assessment</i> Student Metrics</div>".html_safe, course_metrics_path, title: "View Metrics for Identifying Students in
The wording sounds a bit off. Maybe change it to just "Metrics for Identifying Students in Need"

2021-04-29 23:54 UTC, amartinez116 requested changes

2021-04-29 23:54 UTC, amartinez116 commented on app/assets/javascripts/watchlist.js
> +                     <h5> Pending students in need </h5>
"Pending students in need of help"?

2021-04-29 23:54 UTC, amartinez116 commented on app/assets/javascripts/watchlist.js
> +                          <h5> Contacted students in need </h5>
The rest can just be "x students" and no "x students in need"

2021-04-30 23:47 UTC, victorhuangwq commented
![image](https://user-images.githubusercontent.com/5773562/116763820-dff9d400-a9ec-11eb-9fbb-9822fad27113.png)
![image](https://user-images.githubusercontent.com/5773562/116763831-e6884b80-a9ec-11eb-9fb1-a2c2a31e82a2.png)
![image](https://user-images.githubusercontent.com/5773562/116763835-ea1bd280-a9ec-11eb-91ca-cc15e1d6c125.png)

2021-04-30 23:48 UTC, victorhuangwq commented
I have made the appropriate changes. Lmk if this looks good to you

2021-05-02 03:17 UTC, amartinez116 approved these changes
LGTM. We can further discuss wording if you want to change it

2021-05-02 16:07 UTC, merged