Create SECURITY.md
autolab/Autolab pull request #1481
Opened 2022-03-03 17:51 UTC by victorhuangwq

## Description

Creating a security policy

## Motivation and Context

Brought up by #1480 

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2022-03-03 23:36 UTC, oliverli requested changes

2022-03-03 23:36 UTC, oliverli commented on SECURITY.md
> +Send an email to autolab-dev@andrew.cmu.edu to report a vulnerability.
As part of responsible disclosure, be sure to mention that security vulnerabilities should not be publicly disclosed for at least <x> days, to allow us time to address the issue. Of course, also stuff like don't actually test on production, or view/edit other users' data

Also should probably run this one through Dave

2022-03-29 21:50 UTC, xinyis991105 approved these changes
LGTM!

2022-03-29 21:53 UTC, oliverli approved these changes

2022-03-29 21:53 UTC, merged