Force download of attachments
autolab/Autolab pull request #1490
Opened 2022-03-29 22:06 UTC by fanpu

## Description

Cause attachments to be downloaded instead of being opened with the default MIME handler.

I had to also fix the rubocop-rails dependency in the Gemfile.lock as the previous config broke rubocop for me.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2022-04-05 21:43 UTC, victorhuangwq commented on Gemfile
> -  gem 'rubocop', require: false
you might have accidentally removed rubocop from the gemfile

2022-04-06 16:12 UTC, xinyis991105 requested changes
Could you fix Gemfile and Gemfile.lock? Otherwise, LGTM!

2022-04-10 20:44 UTC, fanpu commented
> Could you fix Gemfile and Gemfile.lock? Otherwise, LGTM!

Restored the old Gemfiles, previously I was able to have rubocop working with just rubocop-rails and so thought it superseded rubocop

2022-04-10 20:45 UTC, xinyis991105 approved these changes
LGTM!

2022-04-10 20:52 UTC, merged