Make releaseAllGrades, withdrawAllGrades, etc. POST to prevent CSRF attacks
autolab/Autolab pull request #1512
Opened 2022-04-28 02:21 UTC by 20wildmanj

This PR aims to fix the CSRF vulnerability for 'releaseAllGrades' along with other vulnerable endpoints that previously used GET requests instead of POST.

Thanks to Damien and Fan Pu for the discussion about the security flaw and the useful article here about CSRF and rails:
https://guides.rubyonrails.org/security.html#csrf-countermeasures

## Description
- change releaseAllGrades, withdrawAllGrades, and releaseSectionGrades in the
assessment page to be POST requests, from GET requests.
- turn link_to in the frontend for these actions to be forms with button_to
- changed styling of input classes for danger-zone to look like links, to match
the style of the other actions on the page

## Motivation and Context

We were sent this issue by huntr.dev, where a contributor pointed out this flaw.

## How Has This Been Tested?

Tested mainly through local host, seeing if we can directly access `http://localhost:3000/courses/AutoPopulated/assessments/homework0/releaseAllGrades` from the browser, which should no longer work (should get an error saying there doesn't exist a GET request with that endpoint).

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

@damianhxy

2022-04-28 20:28 UTC, victorhuangwq commented
I'm assuming that you have tested to ensure that releaseAllGrades and withdrawAllGrades still work?

2022-04-29 01:40 UTC, damianhxy commented on app/assets/stylesheets/style.css.scss
> +.danger-side input{
Nit: space before {

2022-04-29 01:46 UTC, damianhxy commented on app/views/assessments/show.html.erb
> +                <%= button_to "Release all grades", {:method => "post" }, {:title=>  "Make all scores for this assessment visible to students", :class=>"", data: {confirm: "Are you sure you want to r
Empty :class can be omitted

2022-04-29 01:51 UTC, damianhxy commented on app/views/assessments/show.html.erb
> +                <%= button_to "Release all grades", {:method => "post" }, {:title=>  "Make all scores for this assessment visible to students", :class=>"", data: {confirm: "Are you sure you want to r
Nit: I think it would be good to have only a single space after :title=>

2022-04-29 02:26 UTC, damianhxy requested changes
Checked that GET routes no longer exist, and POST routes work as expected.

However, it seems that CSRF protection isn't working -- even after deleting the `authenticity_token` fields in a form (or filling them with garbage) and submitting, the request still succeeds. This needs further investigation

2022-04-29 04:34 UTC, 20wildmanj commented
> I'm assuming that you have tested to ensure that releaseAllGrades and withdrawAllGrades still work?
Both methods still work, has been tested.


> Checked that GET routes no longer exist, and POST routes work as expected.
> 
> However, it seems that CSRF protection isn't working -- even after deleting the `authenticity_token` fields in a form (or filling them with garbage) and submitting, the request still succeeds. This needs further investigation

I can confirm that CSRF doesn't seem to be working as intended. I first tried using postman to send a POST request, which actually failed (didn't release grades), but by making just an html file with a form and using that to send a POST request, I was able to release all grades without being on autolab. This definitely seems to be a bit more tricky than originally thought.

2022-04-29 04:55 UTC, 20wildmanj commented
I've added protect_from_forgery to each of the methods (releaseAllGrades etc.) and it now seems that if I try to make a POST request outside of Autolab it should fail:
<img width="1440" alt="Screen Shot 2022-04-29 at 0 53 36" src="https://user-images.githubusercontent.com/25730111/165887118-8e0385a2-c277-4a11-9b52-05e327e22b10.png">

2022-04-29 06:18 UTC, damianhxy commented on app/views/assessments/show.html.erb
> +                <%= form_with :url => { :action => "releaseAllGrades" } do |f| %>
`form_with` and `button_to` can be replaced with `<%= button_to "Release all grades", { :action => "releaseAllGrades" }, {:title=> "Make all scores for this assessment visible to students", data: {confirm: "Are you sure you want to release all grades?"}} %>`

2022-04-29 06:21 UTC, damianhxy commented
> I've added protect_from_forgery to each of the methods (releaseAllGrades etc.) and it now seems that if I try to make a POST request outside of Autolab it should fail: <img alt="Screen Shot 2022-04-29 at 0 53 36" width="1440" src="https://user-images.githubusercontent.com/25730111/165887118-8e0385a2-c277-4a11-9b52-05e327e22b10.png">
> 
> But also I'm not sure if this is ideal if it gives out an error like this?
> 
> EDIT: After restarting the server it seems to give a nicer error message: <img alt="Screen Shot 2022-04-29 at 1 00 39" width="1258" src="https://user-images.githubusercontent.com/25730111/165887559-f6e9b6f0-120a-4ab8-a19a-3cd195f477aa.png">

Confirmed that this fixes the issue. However, it seems weird that `protect_from_forgery` has to be repeated so many times, and there might be some other underlying issue.

Error message shouldn't appear in prod, so that's fine

2022-04-30 20:30 UTC, damianhxy commented on app/controllers/assessments_controller.rb
> +  protect_from_forgery with: :exception
Would be good to figure out why `protect_from_forgery` inside `application_controller.rb` isn't sufficient

2022-04-30 20:30 UTC, damianhxy approved these changes
LGTM!

2022-04-30 20:47 UTC, merged