Better config reload error handling
autolab/Autolab pull request #1522
Opened 2022-05-14 02:55 UTC by damianhxy

Modify course and assessment config reload code to better handle cases where an invalid config is provided

## Description
- Modified course `reload.html` to be consistent with assignment `reload.html`
- Validate syntax of config (via compilation) before saving
- Correctly catch exceptions when attempting to load config files

## Motivation and Context
Currently, course config reload does not set the `@error` variable, so the error page is not correctly rendered.

Furthermore, config reload does not check the syntax of the config file before saving it, meaning that it's possible to reload a file with invalid syntax and corrupt the config.

Also fixes #1516

## How Has This Been Tested?
- Under normal circumstances, course config reload still works
- Under normal circumstances, assessment config reload still works
- Corrupt course config `courses/<course-name>/course.rb` and reload config. Error should be correctly caught and config in `courseConfig/<course-name>.rb` unaffected
- Corrupt assessment config `courses/<course-name>/<assessment-name>/<assessment-name>.rb` and reload config. Error should be correctly caught and config in `assessmentConfig/<course-name>-<assessment-name>.rb` unaffected

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

2022-05-16 20:40 UTC, michellexliu commented on app/controllers/assessments_controller.rb
> +  rescue Exception => e
`rescue Exception` should be avoided + best to avoid disabling the linter; try `rescue SyntaxError` instead

2022-05-16 20:40 UTC, michellexliu commented on app/controllers/courses_controller.rb
> +  rescue Exception => e
same as above

2022-05-16 20:40 UTC, michellexliu requested changes
see comments

2022-05-17 02:23 UTC, damianhxy commented
Note that certain classes of errors (such as `NameError` and `ArgumentError`) will still not be caught. If a user introduces such an error they'll be stuck. There should be a way to gracefully recover from such a mistake (or at the very least, make a backup of last-known good config)

2022-05-18 00:31 UTC, merged