Add UI to upload course and assessment rb files
autolab/Autolab pull request #1883
Opened 2023-04-17 20:56 UTC by damianhxy

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2023-04-22 18:30 UTC, 20wildmanj requested changes
- Ran through testing strategy, checked that rb updating for course and assessments work
- Checked that forms still work
- Checked that deletions don't break anything

Overall, looks good, and lots of nice fixes. Just would like adding support for a label to the file_field before getting this merged.

2023-04-23 17:47 UTC, damianhxy commented on app/form_builders/form_builder_with_date_time_input.rb
> -
Added `:label_text` option, removed line

2023-04-23 17:47 UTC, damianhxy commented on app/form_builders/form_builder_with_date_time_input.rb
> -
<img width="312" alt="Screenshot 2023-04-23 at 13 47 31" src="https://user-images.githubusercontent.com/9074856/233856119-0a2efd89-9aab-4663-88a5-fa7787482422.png">

2023-04-23 17:48 UTC, damianhxy commented on app/views/autograders/_form.html.erb
> +	<%= f.file_field :makefile, button_text: "Autograder Makefile", action: :upload %>
Added label "Autograder Makefile", changed button to "Choose File"

2023-04-23 19:18 UTC, 20wildmanj approved these changes
LGTM

2023-04-23 21:40 UTC, merged