Issue1727
autolab/Autolab pull request #1917
Opened 2023-06-04 13:53 UTC by SimonMen65

## Summary
reviewpad:summary

## Description

Adding columns on how many times of trial has a student do in a certain assignment.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2023-06-04 15:33 UTC, damianhxy commented
Hi @SimonMen65, thank you for your contribution!

To facilitate reviewing, could you ensure the following
- Give a descriptive title to this PR
- Fleshing out the sections of the PR description, including
  - Motivation and Context: mention the issue that this PR closes
  - How has this been tested?: Screenshots of the interface, as well as a bulleted list of any tests you performed + the expected result. For example, performing a submission, creating a missing submission, deleting a submission
  - Type of changes: in this case, it's a new feature
  - Checklist: in this case, you should have run rubocop

Furthermore, regarding the code in this PR
- Avoid changing files unrelated to the PR, such as `database.docker.yml` and `schema.rb`
- Removing debugging code, i.e. the use of `Rails.logger.debug`

2023-07-08 20:15 UTC, 20wildmanj commented
Tested out changes, verified that the Gradebook shows proper version numbers for assessments. I left some comments to be addressed

As an aside, if submissions that are less than the maximum version are destroyed, this would mean that the version number would be "off," but this doesn't really matter in the purpose of having a version number just to see how many times a student has submitted, so not worth addressing.

2023-07-09 17:25 UTC, 20wildmanj requested changes

2023-11-12 17:11 UTC, damianhxy commented
Following up in #2005

2023-11-12 17:11 UTC, closed without merging