Lint views/users
autolab/Autolab pull request #1958
Opened 2023-08-14 17:54 UTC by 20wildmanj

## Summary
reviewpad:summary

## Description

- Run `erblint` on `views/users` using `bundle exec erblint app/users/announcements/*.html.erb -a`
- Refactor `link_to raw('<span class="btn">Delete User</span>')` etc to have html inside of `do` block
- Change success flash for creating user to be more user-friendly

## Motivation and Context

- Part of summer linting

## How Has This Been Tested?

- Verified that creating user works and form renders
- Verified that editing user works and form renders
- users list renders
- LTI launch initialization renders successfully
- buttons for User overview work

## Checklist:

- [x] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting

2023-09-10 18:01 UTC, lykimchee requested changes
- [x] Users list shows up
- [x] Create new user form loads and works (except doesn’t add course, noted inside another comment)
- [x] Editing user form works and loads
- [x] User overview: delete user, change password, revoke token, new api activation, and managed authorized clients buttons all seem to work

2023-09-12 16:37 UTC, 20wildmanj commented on app/views/users/_form.html.erb
> +    <%= f.submit "Create User", { class: "btn primary" } %>
What flow are you using to create the user?

2023-09-12 20:00 UTC, 20wildmanj commented on app/views/users/_form.html.erb
> +    <%= f.submit "Create User", { class: "btn primary" } %>
![Screenshot 2023-09-12 at 3 58 12 PM](https://github.com/autolab/Autolab/assets/25730111/f4ffb980-b4e3-4fcb-98bd-9c9cf12da732)
![Screenshot 2023-09-12 at 3 58 36 PM](https://github.com/autolab/Autolab/assets/25730111/a3d2357e-fbed-4c00-8629-50beda0a131b)

Hopefully your soul can rest now :)

2023-09-12 20:00 UTC, 20wildmanj commented on app/controllers/users_controller.rb
Update flash messages to be more consistent

2023-09-12 20:06 UTC, lykimchee approved these changes
lgtm :>

2023-09-12 20:35 UTC, merged