Manage submissions rebase to master
autolab/Autolab pull request #2047
Opened 2024-01-11 04:33 UTC by michellexliu

## Summary
reviewpad:summary

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop and erblint for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://docs.autolabproject.com/)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

2024-01-16 06:51 UTC, damianhxy requested changes
Followed testing steps from #1893, #1886, and #1990

See comment re: issue with the buttons at the top

2024-01-16 06:51 UTC, damianhxy commented on app/views/submissions/index.html.erb
> +                { title: "Down all submissions from each student",
Nit: typo "Download"

2024-01-16 06:51 UTC, damianhxy commented on app/views/submissions/index.html.erb
> +                missing_course_assessment_submissions_path(@course, @assessment),
These three buttons are linked to the wrong path
- download final -> download all
- download all -> (missing)
- missing submissions -> download final
- manage extensions -> missing submissions
- (missing) -> manage extensions

2024-01-16 06:56 UTC, damianhxy commented on app/views/submissions/index.html.erb
> +    <%= link_to "<i class='material-icons left submissions-icons'>add</i>Create Submission".html_safe.html_safe,
Nit: `.html_safe` used twice

2024-01-16 06:56 UTC, damianhxy commented on app/assets/javascripts/manage_submissions.js
> +})
Nit: undo this removal

2024-01-26 06:42 UTC, damianhxy requested changes
Nits and some regressions

2024-01-29 00:06 UTC, michellexliu commented on app/views/submissions/index.html.erb
> +                { title: "Download final submissions from each student",
https://www.figma.com/proto/XbxY3zscou3HAcc9maC8sl/%5BAutolab%5D-Final-Manage-Submissions-UI?node-id=330-862&scaling=contain&page-id=0%3A1&starting-point-node-id=319%3A1619&hotspot-hints=0

i think in lynn's design we're getting rid of the download all button; it seems that there's not much use case for downloading all submissions for every student
![image](https://github.com/autolab/Autolab/assets/50491000/f2366a5c-eb02-44f0-8662-1f2d7577dd90)

in the new design you can download all of the submissions for an individual student by clicking on the checkmark and hitting "download selected" (feature to be implemented in a future PR once grouping is implemented)
![image](https://github.com/autolab/Autolab/assets/50491000/8bb56772-3786-4dfd-a054-86f80ca2cacd)

2024-02-03 21:06 UTC, damianhxy commented on app/views/submissions/index.html.erb
> +                { title: "Download final submissions from each student",
Ahh okay

2024-02-03 21:08 UTC, damianhxy approved these changes
LGTM

2024-02-04 08:28 UTC, merged