Fix scoreboard sorting failing on custom scoreboardOrderSubmissions, add more error checking when creating scoreboard entries / displaying
autolab/Autolab pull request #2092
Opened 2024-02-17 21:42 UTC by 20wildmanj

## Description

- Adds more error-catching logic when calling custom `scoreboardOrderSubmissions`, in the case that an exception is raised, and tells the instructor via an error message
- Adds a rescue block to the top-level sort call in `#show` so that if a bad sort / comparison occurs, the error can be caught
- Instead of returning scoreboard entries with "-" on errors, raise an error, and in `#show`, revert to an empty array
- In the `#show` view code, check that the current entry length is greater than the index in order to show a score, else show an error icon (which handles the empty array case)
- Fix up logging, add more specific errors to be returned to instructors, and redirect students back to assessments index

## Motivation and Context

Closes #2086 

## How Has This Been Tested?

Import the provided assessment:
[randomlab5_20240217.tar.zip](https://github.com/autolab/Autolab/files/14320229/randomlab5_20240217.tar.zip)

1. Upload at least two submissions as students
2. View scoreboard, see that it renders fine (if it is not rendering fine, upload `autograder.tar`as the autograder)
3. Upload the assessment config file `randomlab5-bad-scoreboard-order.rb` (in Edit Assessment you can upload)
  - this test returns a bad sort, causing an ArgumentError
5. See that you get an error as follows:
![Screenshot 2024-02-17 at 3 22 59 PM](https://github.com/autolab/Autolab/assets/25730111/7b66661a-439f-464d-929c-d47805d7e426)
6. Try to view scoreboard as a student and see that you get redirected back to assessment index with an error flash
7. Upload the initial assessment config file back, and then upload `autograde-bad.tar` as the new autograder
 - this autograder returns just a number instead of an array
9. Regrade all submissions
10. view scoreboard as instructor, see that following error appears:
![Screenshot 2024-02-17 at 3 59 06 PM](https://github.com/autolab/Autolab/assets/25730111/a23887cf-ef99-4f2e-80ef-0e1d3b28938d)
11. View scoreboard as student, see that scoreboard is visible but error icons appear:
![Screenshot 2024-02-17 at 4 03 59 PM](https://github.com/autolab/Autolab/assets/25730111/18ed6c9e-4259-4cea-9e98-c9421b9f2265)
12. Upload the old autograder.tar back, and regrade all
13. Then add this code after line 296 in `scoreboards_controller.rb`:
```
if [true, false].sample
      parsed["scoreboard"] = []
    end
```
( you may need to also reload the config file)
  - this replicates the scenario where sometimes the scoreboard results aren't correct / autograder failed
14. view the scoreboard as an instructor, see the following error
![Screenshot 2024-02-17 at 4 41 53 PM](https://github.com/autolab/Autolab/assets/25730111/59c4c601-641e-42d7-98e7-7c3bc37c8cab)

15. As a student, see something like this (all the bad scoreboard entries are at the bottom)
![Screenshot 2024-02-17 at 2 30 28 PM](https://github.com/autolab/Autolab/assets/25730111/3bf4a73c-1d8b-44dc-8fff-56d600d049b4)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

2024-02-18 07:13 UTC, damianhxy commented on app/views/scoreboards/show.html.erb
>                    <%= render 'error_icon' %>
@20wildmanj This was introduced by #1982 and unfortunately is in production rn

![Screenshot 2024-02-18 at 02 13 34](https://github.com/autolab/Autolab/assets/9074856/c00f6fe8-ffc9-40bd-95e6-65ed0b26f9d9)

2024-02-18 15:21 UTC, cg2v commented on app/views/scoreboards/show.html.erb
>                    <%= render 'error_icon' %>
I removed the 'q' from the production instance

2024-02-18 15:32 UTC, damianhxy commented on app/views/scoreboards/show.html.erb
>                    <%= render 'error_icon' %>
Thanks! The symbol tree also doesn't seem to be working in prod, are the new systems missing ctags?

2024-02-19 18:44 UTC, 20wildmanj commented on app/views/scoreboards/show.html.erb
>                    <%= render 'error_icon' %>
Added a commit to remove the typo, sorry for not catching this earlier!

2024-02-21 07:32 UTC, damianhxy commented
When updating the assessment rb file, if you go straight to the scoreboard (i.e. don't load the assessment index page), there is an error about an undefined method.

![Screenshot 2024-02-21 at 02 19 53](https://github.com/autolab/Autolab/assets/9074856/d178404c-5859-4ea0-b1db-f4b242f9febb)

However, after loading the assessment index page at least once, the error message is now as expected

![Screenshot 2024-02-21 at 02 31 54](https://github.com/autolab/Autolab/assets/9074856/3898cc63-47c8-44cb-8175-c0848b2189b7)


Suspect it is because `reload_config_file` is not called by `assessments_controller.rb#update`

2024-02-21 07:58 UTC, damianhxy requested changes
Functionality generally looks good, but left some nits

2024-02-21 07:58 UTC, damianhxy commented on app/controllers/scoreboards_controller.rb
> +          "submissions . Please make sure your scoreboard results are returned " \
Nit: extra space before period

2024-02-21 07:58 UTC, damianhxy commented on app/controllers/scoreboards_controller.rb
> +        !parsed["scoreboard"].is_a?(Array)) &&
Extraneous `&&`?

2024-02-21 07:58 UTC, damianhxy commented on app/controllers/scoreboards_controller.rb
> +    raise StandardError if !parsed || !parsed.is_a?(Hash) || !parsed["scoreboard"] ||
Why not move this raise into the `if`-block above?

2024-02-23 03:53 UTC, 20wildmanj commented on app/views/scoreboards/show.html.erb
> +    <pre><%= @error %></pre>
Removed the @error field

2024-02-23 03:54 UTC, 20wildmanj commented on app/views/scoreboards/show.html.erb
> +    <pre style="text-wrap: wrap;"><%= @errorMessage %></pre>
Changed how the wrapping works:

Chrome:
![Screenshot 2024-02-22 at 10 51 32 PM](https://github.com/autolab/Autolab/assets/25730111/b742dcac-5a7b-4d01-b331-48b59713eb1c)

Firefox:
![Screenshot 2024-02-22 at 10 51 50 PM](https://github.com/autolab/Autolab/assets/25730111/cc661d50-c9d9-4c1c-a628-fc45f7febf99)

Safari:
![Screenshot 2024-02-22 at 10 52 32 PM](https://github.com/autolab/Autolab/assets/25730111/b0b7d731-14a1-47b4-a57f-67cbae93a945)

2024-02-23 04:06 UTC, 20wildmanj commented
> When updating the assessment rb file, if you go straight to the scoreboard (i.e. don't load the assessment index page), there is an error about an undefined method.
> 
> ![Screenshot 2024-02-21 at 02 19 53](https://private-user-images.githubusercontent.com/9074856/306534978-d178404c-5859-4ea0-b1db-f4b242f9febb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjA2NjksIm5iZiI6MTcwODY2MDM2OSwicGF0aCI6Ii85MDc0ODU2LzMwNjUzNDk3OC1kMTc4NDA0Yy01ODU5LTRlYTAtYjFkYi1mNGIyNDJmOWZlYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDM1MjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgyODE4NDUxNTUyYWM0NDkzNjVkMjU3NWZiNjlmZjNmZTFkODU1ZWY0MDAzNWEyMzQ2ZmI3OWY2YmY1NmY2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.So3kwpu8s296wYnHRlrcE3-t8x8WXd78OCyTWXbmJq4)
> 
> However, after loading the assessment index page at least once, the error message is now as expected
> 
> ![Screenshot 2024-02-21 at 02 31 54](https://private-user-images.githubusercontent.com/9074856/306535157-3898cc63-47c8-44cb-8175-c0848b2189b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjA2NjksIm5iZiI6MTcwODY2MDM2OSwicGF0aCI6Ii85MDc0ODU2LzMwNjUzNTE1Ny0zODk4Y2M2My00N2M4LTQ0Y2ItODE3NS1jMDg0OGIyMTg5YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDM1MjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzhkNDQ5NzEzOWVjYTE2NmI0M2VmMGEyOGI4NmQ3YzljZGU5MmRmNTQxZTc3NGRmM2JmMWFhMWVlMjAzYzljYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2LFn6VdVL81UZwe__Shu8L5LxVYAv6wD29tiJotRK_8)
> 
> Suspect it is because `reload_config_file` is not called by `assessments_controller.rb#update`

I noticed this while testing, not sure why going to index would resolve this though because doesn't seem that index doesn't do any calls to reload the config file? Not sure if it's worth looking into a fix for a hook that very few classes use (and the ones that do should understand how to reload the config file)

2024-02-24 18:25 UTC, damianhxy approved these changes
Ran through testing workflow, LGTM

2024-02-24 21:48 UTC, merged