Edit disable subs
autolab/Autolab pull request #2224
Opened 2024-09-27 20:52 UTC by jhs-panda

## Description

Adjusted UI to make the "Disable Autolab submissions" button and functionality more noticeable. Also edited description on submissions page.
Before:
<img width="1054" alt="Screen Shot 2024-09-27 at 4 41 53 PM" src="https://github.com/user-attachments/assets/6d773e0b-8cde-4a21-8f8b-112a6c9a895d">
<img width="827" alt="Screen Shot 2024-09-27 at 4 46 38 PM" src="https://github.com/user-attachments/assets/931bc48a-305d-40e5-a273-ffe86bae87f0">

After:
<img width="1069" alt="Screen Shot 2024-09-27 at 4 44 31 PM" src="https://github.com/user-attachments/assets/86ce7d99-c2b5-41d4-9a54-8604cc4918fc">
<img width="1045" alt="Screen Shot 2024-09-27 at 4 44 43 PM" src="https://github.com/user-attachments/assets/3209cbdd-96c5-4e64-9e71-76d29dd6063e">
<img width="879" alt="Screen Shot 2024-09-27 at 4 45 57 PM" src="https://github.com/user-attachments/assets/4e579742-82e7-4289-8abf-b8bb781e0879">

## Motivation and Context

Some classes have assignments that shouldn't be submitted through Autolab. The functionality for disabling submissions through Autolab exists, but it is currently a bit unclear what the button does and many classes therefore don't use it. 

## How Has This Been Tested?

Tested locally (see screenshots) to make sure changes were saved and toggle between disable/enable handins and gray-out worked as expected.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run rubocop and erblint for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://docs.autolabproject.com/)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

2024-10-25 19:53 UTC, evanyeyeye requested changes
Mostly looks good!

However, this PR forces the "Handin filename" field to always be `handin.c` on the frontend view, even when it has been successfully modified.

Also, I noticed that in your "After" screenshot the "Autograder settings" button is gone in the left navigation column. Is that an effect of the PR?

2024-10-27 15:38 UTC, jhs-panda commented
> However, this PR forces the "Handin filename" field to always be `handin.c` on the frontend view, even when it has been successfully modified.

I believe I have corrected this my recent commits.

> Also, I noticed that in your "After" screenshot the "Autograder settings" button is gone in the left navigation column. Is that an effect of the PR?

Sorry, I chose different assessments pages to screenshot and one of them wasn't an autograded assignment. I've corrected the image in the "After" screenshot.

Thanks!

2024-11-14 17:06 UTC, jhs-panda commented on app/views/assessments/_edit_handin.html.erb
> +                 class: "handin-filename-field" %>
Functionality doesn't work, tried.

2024-11-14 17:08 UTC, jhs-panda reviewed
Processed suggested edits and CodeRabbit suggestions.

2024-11-15 04:24 UTC, jhs-panda commented on app/views/assessments/_edit_handin.html.erb
> +                 class: "handin-filename-field" %>
Took the suggestion for the most part, excluded hyphens because its inclusion allowed other invalid characters to be used without flashing error.

2025-03-17 08:10 UTC, jhs-panda commented on app/views/assessments/_edit_handin.html.erb
> +                 title: "Only alphanumeric characters, dots, hyphens, and underscores are allowed." %>
We want to include hyphens.

2025-03-17 14:23 UTC, jhs-panda commented
> Also, the sanitization for handin filename is probably a little too restrictive. For example, hyphens are used pretty regularly for 15213 assessments.
For some reason, allowing hyphens lets any type of character in the filename (adding hyphens was suggested by CodeRabbit before and any filename was allowed). That's why I removed it and allowed the other characters. If we want it to be on the profs' side to have valid filenames, it's fine. Otherwise, allowing hyphens in the pattern will mess up any filename error checking.

2025-03-24 18:26 UTC, evanyeyeye requested changes
The edge case fix seems to work, but its a bit hacky. Not sure if this is the best way to do things, but I think it suffices for now. Regarding the hyphen, it will work if you escape it with two backslash characters. However, I'm not sure if we can fully account for all handin filenames used by current courses. Maybe we want to give instructors more freedom on this.

2025-04-14 19:25 UTC, evanyeyeye commented
LGTM.

2025-04-14 19:26 UTC, evanyeyeye approved these changes
LGTM!

2025-04-15 22:51 UTC, merged