Manage Submissions
autolab/Autolab pull request #2248
Opened 2024-12-05 22:54 UTC by KesterTan

## Description
This is an initial PR for the revamp of Manage Submissions. This would resolve #1903. 

## How Has This Been Tested?
Navigate to Manage Submissions. Test that all buttons work as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] I have run rubocop and erblint for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://docs.autolabproject.com/)
- [ ] I have updated the documentation accordingly, included in this PR

2025-01-13 19:41 UTC, KesterTan commented on app/assets/stylesheets/style.css.scss
> +}
Fixed.

2025-01-13 19:47 UTC, KesterTan commented on app/controllers/assessments_controller.rb
> +  end
Edited and changed.

2025-01-16 16:07 UTC, dwang3851 requested changes
Overall functionality works, I tested create submission, download final submissions, missing submissions, manage extensions, and regrade/delete/download/excuse selected. 

One large issue I found was that after regrading a submission from create submission, the regrade was successful, but the updated score does not show up in the score column. 

Other smaller issues that we can potentially address later (or ask new members to try fixing):
- Search bar is unintuitive, if you type the exact string the expected user shows up, but a bunch of unexpected users also show up. (eg. searching for "john f" also returns "john k")
- Might be desirable to have some indication if the autograder has not been run on a submission if it was created through create submissions or missing submissions

2025-01-26 05:20 UTC, KesterTan commented
I think the above could be because of the late penalty was applied, resulting in the submission's score being zero.

2025-01-26 17:35 UTC, dwang3851 approved these changes
New functionality works, lgtm

2025-01-27 22:32 UTC, coder6583 commented
![image](https://github.com/user-attachments/assets/4092e68c-b7da-4bc7-a383-70ef8be8693f)
When we click on the score details, the final score and the late penalty seems to be undefined.

2025-01-27 22:48 UTC, coder6583 commented
![image](https://github.com/user-attachments/assets/0e764a04-c1cb-4685-9d75-9ec04efca6aa)
Maybe put the close button on the top right instead of middle of the header

2025-01-27 22:51 UTC, coder6583 commented
![image](https://github.com/user-attachments/assets/ca788a86-2a49-499d-9b2b-b8aa76857925)
It might be helpful to put the unexcuse button in a place where it's easier to find. Maybe be able to unexcuse with the excuse selected button

2025-01-27 23:01 UTC, coder6583 commented
I noticed that the pagination of manage submissions was gone. I was trying to access the manage submission page of a course with about 1000 users, and it seemed to take a really long time.
![image](https://github.com/user-attachments/assets/613a4e42-183c-47b7-ab56-8350b9240b91)
Original Manage Submissions
![image](https://github.com/user-attachments/assets/05da66bf-da9d-4a91-8318-41d07c325deb)
New Manage Submissions

2025-01-27 23:03 UTC, coder6583 commented
> I noticed that the pagination of manage submissions was gone. I was trying to access the manage submission page of a course with about 1000 users, and it seemed to take a really long time. ![image](https://private-user-images.githubusercontent.com/38949473/407119845-613a4e42-183c-47b7-ab56-8350b9240b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwMTkxOTUsIm5iZiI6MTczODAxODg5NSwicGF0aCI6Ii8zODk0OTQ3My80MDcxMTk4NDUtNjEzYTRlNDItMTgzYy00N2I3LWFiNTYtODM1MGI5MjQwYjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI3VDIzMDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzU2YzkwMTczMDZiODg2YjhlODZkZTAyNmRhZTRlNDRmOTU1NDYyNGE2Mjg2MTM2ZjhkNzRmZWM3OTE5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FEnPSqNVY7sFgHyZvSgG_DHfHzzjVYAsGMYoMKLZjpU) Original Manage Submissions ![image](https://private-user-images.githubusercontent.com/38949473/407119954-05da66bf-da9d-4a91-8318-41d07c325deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwMTkxOTUsIm5iZiI6MTczODAxODg5NSwicGF0aCI6Ii8zODk0OTQ3My80MDcxMTk5NTQtMDVkYTY2YmYtZGE5ZC00YTkxLTgzMTgtNDFkMDdjMzI1ZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI3VDIzMDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODBkMjFkNzNkOWFmYTMxMmNiZWU1NWQ3MzI1NTA3MGY0NjU0MGUxMjQ5ZWRiNjlmODU0MzljNThjNDQxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BQaJpIfGGDorW3bdLAH4RpO_xSxZ-lFfYdGsQ5zNOeI) New Manage Submissions

Clicking the select all seems to take a really long time, might be related to this.

2025-01-28 00:42 UTC, KesterTan commented
![Screenshot 2025-01-27 at 7 41 34 PM](https://github.com/user-attachments/assets/618366cd-995d-4471-8767-251288d7b8a2)
Score details with fixed final score and late penalty, close button is also shifted to top right corner.

2025-01-30 05:28 UTC, KesterTan commented
Added pagination and style fixes for popup. With pagination, I tweaked it such that only 100 entries appear per page which means that only 100 entries can be selected with select all (i think it is not intuitive to have select all select 1000 entries when you can only see 100, as such #2261 is not a concern for now.

Additionally, the unexcuse button was placed there because you can select any students (excused and unexcused) so toggling the same button would not work. I think adding an additional unexcuse selected button would be out of the scope of the PR so won't fix for now.

<img width="1159" alt="Screenshot 2025-01-30 at 12 24 26 AM" src="https://github.com/user-attachments/assets/e1e85243-0a9d-4e7d-a02b-f7b216f95b55" />

2025-01-30 15:41 UTC, jhs-panda commented on app/views/submissions/index.html.erb
> +  <% headers = ["Submitted By",
It seems as though IP Address was removed from the headers present on the manage submissions page. Not sure if this was intentional or not and if instructors found it useful in the previous version of manage submissions.

2025-02-02 17:58 UTC, jhs-panda commented
Regarding the excuse/unexcuse option, maybe just adding an explanation like "Click to unexcuse" when hovering over the "EXCUSED" option and changing it to a darker shade might help. As long as there is some indication other than clicking on the "EXCUSED" text to indicate clicking it can unexcuse the student, it should be fine?
Something similar is done for the View File button:
<img width="897" alt="image" src="https://github.com/user-attachments/assets/f8affee1-3f83-40cd-913c-f3329ff45fef" />

2025-02-02 19:20 UTC, coder6583 approved these changes
I think we might need improvements for the tweak UI but LGTM!

2025-02-02 19:20 UTC, jhs-panda approved these changes
LGTM

2025-02-02 19:41 UTC, merged